name: Build the plugin

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: bash build.sh

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{github.event.repository.name}}
          path: |
            target/*.zip
            target/*.tar.gz